---
language: python
python: "2.7"
sudo: false

env:
  - PLAYBOOK=playbook-provision.yml ROLES_PLAYBOOK=playbook-roles.yml ANSIBLE_ROOT=ubuntu-12.04-x86_64/beetbox/ansible

addons:
  apt:
    packages:
    - curl

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Create config files.
  - touch $ANSIBLE_ROOT/beetbox.config.yml
  - touch $ANSIBLE_ROOT/project.config.yml
  - touch $ANSIBLE_ROOT/vagrant.config.yml

  # Install galaxy roles.
  - ansible-playbook $ANSIBLE_ROOT/$ROLES_PLAYBOOK -i "localhost,"

script:

  # Check playbook-roles.yml syntax.
  - "ansible-playbook $ANSIBLE_ROOT/$ROLES_PLAYBOOK --syntax-check"

  # Check playbook-provision.yml syntax.
  - "ansible-playbook $ANSIBLE_ROOT/$PLAYBOOK --syntax-check"
