---
language: python
python: "2.7"

env:
  - PLAYBOOK=playbook.yml ANSIBLE_ROOT=ubuntu-12.04-x86_64/ansible ANSIBLE_CONF=ubuntu-12.04-x86_64/example/vagrant.ansible.yml.default

before_install:
  - sudo add-apt-repository ppa:ondrej/php5 -y
  - sudo apt-get update -q
  - sudo apt-get update -qq
  - sudo apt-get install curl
  - cp $ANSIBLE_CONF $ANSIBLE_ROOT/box.config.yml

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install required dependencies.
  - ansible-galaxy install -r $ANSIBLE_ROOT/requirements.yml

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook $ANSIBLE_ROOT/$PLAYBOOK -c local -i 'localhost,' --syntax-check"