# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  dir = File.dirname(File.expand_path(__FILE__))
  $vagrant_config = "#{dir}/config.yml"
  config.vm.box = "8thom/acquia-devbox"

end
